In [1]:
import sys
for entry in sys.path:
    if 'python2.7' in entry:
        sys.path.remove(entry)

In [2]:
sys.path.remove('/usr/local/lib/python2.7/site-packages/mxnet-0.9.1-py2.7-macosx-10.11-x86_64.egg')

In [3]:
import numpy as np
z = np.matrix('0.4; 0.8')

In [4]:
w0 = np.matrix('0.1 0.3; 0.7 0.9; 0.5 0.7; 0.1 0.9; 0.3 0.1; 0.4 0.6; 0.7 0.8; 0.2 0.1')

In [5]:
b0 = np.matrix('0.1; 0.4; 0.2; 0.3; 0.5; 0.9; 0.7; 0.9')

In [6]:
h0 = np.matmul(w0, z) + b0

In [7]:
h0 = np.array(h0)

In [8]:
h1 = h0.reshape((2, 2, 2))

In [9]:
h1_1_pad = np.pad(h1[0,:,:], ((2, 2), (2, 2)), 'constant')

In [10]:
h1_2_pad = np.pad(h1[1,:,:], ((2, 2), (2, 2)), 'constant')

In [11]:
h1_2_pad.shape

(6, 6)

In [12]:
w1_1 = np.array([[0.1, 0.4, 0.5], [0.1, 0.7, 0.1], [0.2, 0.4, 0.3]])

In [13]:
w1_2 = np.array([[0.2, 0.1, 0.6], [0.3, 0.9, 0.2], [0.5, 0.2, 0.3]])

In [14]:
b1 = np.array([[0.1, 0.5, 0.6, 0.3], [0.2, 0.4, 0.8, 0.1], [0.1, 0.3, 0.7, 0.2], [0.3, 0.1, 0.2, 0.1]])
b1.shape

(4, 4)

In [15]:
h1_1_pad.shape

(6, 6)

In [16]:
from scipy import signal
conv_first_channel = signal.convolve2d(h1_1_pad, w1_1, 'valid')
conv_second_channel = signal.convolve2d(h1_2_pad, w1_2, 'valid')
conv_first_channel

array([[ 0.038,  0.292,  0.75 ,  0.7  ],
       [ 0.134,  0.896,  1.922,  0.67 ],
       [ 0.172,  1.21 ,  1.512,  0.526],
       [ 0.192,  0.596,  0.712,  0.318]])

In [17]:
h2 = conv_first_channel + conv_second_channel + b1

In [18]:
h2_flatten = h2.flatten()

In [19]:
w2 = np.array([[0.1, 0.2, 0.3, 0.2, 0.4, 0.6, 0.7, 0.1, 0.1, 0.2, 0.5, 0.3, 0.1, 0.2, 0.6, 0.9]])

In [20]:
w2.shape

(1, 16)

In [21]:
import math

def sigmoid(x):
    return 1 / (1 + math.e ** -x)

In [22]:
prob = sigmoid(np.matmul(w2, h2_flatten) + 0.3)

In [23]:
prob

array([ 0.99999743])

In [24]:
w1 = np.dstack((w1_1, w1_2)).shape

In [25]:
w1

(3, 3, 2)

In [26]:
h2

array([[ 0.278,  1.17 ,  1.924,  1.924],
       [ 0.868,  2.762,  5.326,  1.714],
       [ 1.108,  4.196,  4.008,  1.4  ],
       [ 1.302,  1.55 ,  1.61 ,  0.736]])

In [27]:
np.matmul(w2, h2_flatten) + 0.3

array([ 12.8704])